services:
  od-ash_tray:
    build:
      dockerfile: Dockerfile.ci
    ports: 
      - "0.0.0.0:7377:7377"
    environment:
      - ASH_TRAY_ID=ash
      - ASH_TRAY_DIRECTORY=/cdn
      - ASH_TRAY_KEY=aaaaaVVVVVVVAAAAAAAAaaaaaaaaaaaa
      - ASH_TRAY_PORT=7377
    volumes:
      - ./cdn:/cdn:rw
