services:
  od-ash_tray:
    image: "${OD_ASH_TRAY_IMAGE:?OD_ASH_TRAY_IMAGE must be set}"
    pull_policy: always
    ports: 
      - "127.0.0.1:7377:7377"
    environment:
      - ASH_TRAY_ID
      - ASH_TRAY_DIRECTORY=/cdn
      - ASH_TRAY_KEY
      - ASH_TRAY_PORT=7377
    volumes:
      - /cdn:/cdn:rw
