FROM golang AS build
WORKDIR /app
COPY main.go main.go
COPY utils.go utils.go
COPY go.sum go.sum
COPY go.mod go.mod

RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux go build -o /od-ash-tray .

CMD ["/od-ash-tray"]

